### ISSUE TITLE
Build failed for creating android package

### ISSUE THREAD

**Issue by yq2018** [Chinesee/eason-club#11]
Hi Codennn,

Last week I want to find an App to keep contact with club members, and I found eason-club project.
When I try to build android apk, it is failed. I have tried to solve problem for several days, the problem is still there.

The environment and the steps is as following:
1. Ubuntu 16.04.7 64bit in VMware WS
2. Node.js v12.22.6
3. NPM v6.14.15 ( v7.24.0 has same result)
4. @react-native-community/cli-platform-android@5.0.1
5. @react-native-community/cli@5.0.1

The error message is as following:
```
linux@ubuntu:~/app/eason-club/android$ ./gradlew assembleRelease
:ReactNative:Unexpected empty result of running '[node, -e, console.log(require('react-native/cli').bin);]' command.
:ReactNative:Running '[node, -e, console.log(require('react-native/cli').bin);]' command failed.
FAILURE: Build failed with an exception.

* Where:
Script '/root/eason-club/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 205

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:818  throw err;  ^Error: Cannot find module 'react-native/cli'Require stack:- /root/eason-club/android/[eval]    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)    at Function.Module._load (internal/modules/cjs/loader.js:667:27)    at Module.require (internal/modules/cjs/loader.js:887:19)    at require (internal/modules/cjs/helpers.js:74:18)    at [eval]:1:13    at Script.runInThisContext (vm.js:120:18)    at Object.runInThisContext (vm.js:309:38)    at Object.<anonymous> ([eval]-wrapper:10:26)    at Module._compile (internal/modules/cjs/loader.js:999:30)    at evalScript (internal/process/execution.js:94:25) {  code: 'MODULE_NOT_FOUND',  requireStack: [ '/root/eason-club/android/[eval]' ]}
```
I have tried following steps:
1. nmp install react-native/cli, there is no module available.
2. Searching according above error message, one sulution is to install @react-native-community/cli. The module is already installed, the solution is not correct.
3. Searching according above error message, another sulution is to install expo-cli. The solution is incorrect too.

Full scan information can be found [here.](https://scans.gradle.com/s/ydgu35sg7izsi)

Could you share your build environment to help me clone it? Or could you give any suggestion?

Thank you very much.

BR,
Qian

**Comment by Codennnn** [comment]
抱歉！现在才看到你的 issue。
这个项目自我建立以来，基本没怎么维护，不过我计划在近期继续开发这个项目，完善文档。
你可以留下你的联系方式吗，以便在我完成之后联系你。

**Comment by yq2018** [comment]
太好了，可以发邮件给我： bzd8042@gmail.com

**Comment by Codennnn** [comment]
随着技术发展，开发该项目时所用的技术与当前技术已经相去甚远。目前看来，我已经没有精力再维护这个项目了，我很抱歉。
